extends Node

enum ROOMS {
	LOBBY, TOILET, GROOMING, CORRIDOR, SUPPLY_ROOM, SWEATSHOP, STAFF_ROOM,
	CEO_OFFICE, KENNEL, MEAT_ROOM
}

# Public transitions only
# Hidden shortcuts (triggered through actions) : SUPPLY_ROOMS -> SWEATSHOP, KENNEL -> MEAT_ROOM
func transition (room: ROOMS):
	match room:
		ROOMS.LOBBY :      [ROOMS.TOILET, ROOMS.GROOMING, ROOMS.GROOMING]
		ROOMS.TOILET:      [ROOMS.GROOMING]
		ROOMS.GROOMING:    [ROOMS.LOBBY, ROOMS.LOBBY, ROOMS.SUPPLY_ROOM, ROOMS.CORRIDOR]
		ROOMS.CORRIDOR:    [ROOMS.GROOMING, ROOMS.SUPPLY_ROOM, ROOMS.CEO_OFFICE, ROOMS.STAFF_ROOM, ROOMS.KENNEL]
		ROOMS.SUPPLY_ROOM: [ROOMS.CORRIDOR]
		ROOMS.SWEATSHOP:   [ROOMS.SUPPLY_ROOM]
		ROOMS.STAFF_ROOM:  [ROOMS.CORRIDOR]
		ROOMS.CEO_OFFICE:  [ROOMS.CORRIDOR]
		ROOMS.KENNEL:      [ROOMS.CORRIDOR]
		ROOMS.MEAT_ROOM:   [ROOMS.KENNEL]
